# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TinyRests
author: TinyRests
email: salmorejo2024@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple, free online calculator to create the perfect nap schedule for your toddler.
  Adjust times based on age, wake-up time, and bedtime to get a customized daily nap plan.
baseurl: "/NapCalc" # the subpath of your site, which is your repository name (case sensitive)
url: "https://iushakovsky.github.io" # your GitHub Pages URL
production_url: https://iushakovsky.github.io/NapCalc
github_username: napcalc

# SEO settings
lang: en_US
twitter:
  username: tinyrests
  card: summary_large_image
logo: /assets/img/og-image.jpg
social:
  name: TinyRests
  links:
    # - https://twitter.com/tinyrests
    - https://github.com/napcalc
webmaster_verifications:
  google: # Add your Google verification code here
  bing: # Add your Bing verification code here

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
